main/urls.py
from django.urls import path

from . import views


app_name = 'main'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView


urlpatterns = [
    path('main/', include('main.urls')),
    # path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    
    # path('', TemplateView.as_view(template_name='home.html'), name='home'), 
    # path('', TemplateView.as_view(template_name='login.html'), name='login'), 
]

templates/base.html
{% load static %}
 
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>
 
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.4.1-dist/css/bootstrap.min.css' %}" rel="stylesheet">
 
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head_css %}{% endblock %}
    {% block head_js %}{% endblock %}
    
  </head>
  <body>
    {#% block navbar %}{% endblock %#}
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
              <span class="sr-only">切换导航条</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Mysite</a>

          </div>
   
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="my-nav">
            {% if request.user.is_authenticated %}
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'main:index' %}">主页</a></li>
              <li class=""><a href="#">iOS</a></li>
              <li><a href="#">SVN</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Java
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">jmeter</a></li>
                    <li><a href="#">EJB</a></li>
                    <li><a href="#">Jasper Report</a></li>
                    <li class="divider"></li>
                    <li><a href="#">分离的链接</a></li>
                    <li class="divider"></li>
                    <li><a href="#">另一个分离的链接</a></li>
                </ul>
              </li>
            </ul>
            {% endif %}

            <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
              <li><span class="sr-only">username</span></li>
              <li><a href="{% url 'main:logout' %}">退出</a></li>
              {% else %}
              <li><a href="{% url 'main:login' %}">登录</a></li>
              <li><a href="{% url 'main:register' %}">注册</a></li>
              {% endif %}
            </ul>

          </div>
        </div>
      </nav>

    {% block content %}{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>

    {% block body_js %}{% endblock %}

  </body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}


<div class="col-md-4 col-sm-6 border p-0 offset-md-4 offset-sm-6 my-5">
    <h3 class="text-center bg-info p-2 text-white mb-0">登录</h3>
    <form class='p-5 bg-white' action="/polls/login/" method="post">
        {% if message %}
            <div class="alert alert-warning">{{ message }}</div>
        {% endif %}
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }}
            {{ form.password }}
        </div>
        <div class="form-group">
            {{ form.captcha.errors }}
            {{ form.captcha.label_tag }}
            {{ form.captcha }}
        </div>
        <div class="pt-3 pb-5">
            <button type="submit" class="btn btn-primary pull-left mb-5">立即登录</button>
            <a class="btn btn-danger pull-right mb-5" href="/user/register/">前往注册</a>
        </div>
    </form>
</div>
{% endblock content %}